### ISSUE TITLE
Ports and trading confusion

### ISSUE THREAD

**Issue by alexweininger** [alexweininger/android-catan#278] opened 2018-12-02 22:24 UTC
Selecting ports and trading with port / bank is confusing.

**Comment by alexweininger** [comment] 2018-12-03 03:41
Being fixed along with #277 by @dborg291

**Comment by dborg291** [comment] 2018-12-05 00:34
The issue was a duplicate of #277. The issue has been addressed, see #277 for more information.

**Closed as completed by dborg291** 2018-12-05 00:34 UTC
Labels: bug, duplicate
